get: 
  tags: 
    -  Product
  summary: Get a product by ID
  description:  |
    Get a product by ID
  operationId: getProductById
  parameters: 
    - $ref: ../../components/parameters/product_id.yaml
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product.yaml
    "400":
      description: Bad request due to invalid input.
    "404":
      description: Customer not found.
    "500":
      description: Internal server error.